version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: ligue-lead-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ligue-lead
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - project-network

  app:
    build: .
    container_name: ligue-lead-app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: root
      DB_NAME: ligue-lead
    depends_on:
      - db
    networks:
      - project-network
    volumes:
      - .:/app

volumes:
  db_data:

networks:
  project-network:
